### ISSUE TITLE
Provide us with your use case

### ISSUE THREAD

**Issue by brucellino** [sci-gaia/LagosHackfest#13]
Dear participant.

Please provide us with the link to the github repository that you will be using during the hackfest.

Thanks !
Bruce

**Comment by yosephabate** [comment]
github repo: https://github.com/yosephabate/addisriversmonitor

**Comment by brucellino** [comment]
Thanks  ! I'm adding it to the hackfest board https://waffle.io/sci-gaia/LagosHackfest/ come and see.

**Comment by brucellino** [comment]
Can you let me know who else is working on this project ? Provide their github user name please - thanks !

**Comment by yosephabate** [comment]
Currently I am the only one working on Addis Ababa Rivers/Riverside Monitoring System. The other project we are working on is Education eLibrary and Repository with Behailu Osro @behailukorma

**Comment by brucellino** [comment]
:ok:
