### ISSUE TITLE
Please provide us with your ORCID

### ISSUE THREAD

**Issue by brucellino** [sci-gaia/LagosHackfest#27]
Hi ! 

in order to publish your research in the Sci-GaIA Open Access Repository, you need to have an ORCID. Please respond to this ticket with your ORCID : e.g. orcid.org/0000-0002-6607-7145

If you do not have one, please sign up at https://orcid.org/register

**Comment by adedeji19** [comment]
orcid.org/0000-0002-7797-8272

**Comment by brucellino** [comment]
Thanks @adedeji19  - can you update some of the information in your profile when you have some time ?
