### ISSUE TITLE
create the repo for the D4PR

### ISSUE THREAD

**Issue by brucellino** [sci-gaia/LagosHackfest#56]

**Comment by ezeasorekene** [comment]
https://github.com/unizik/D4PR

**Comment by brucellino** [comment]
great, as soon as you have the php code for the website in there, I'll close the ticket.

**Comment by ezeasorekene** [comment]
Hi @brucellino you can check the repo now.... It has content at the moment... @domisky2003 @icuzochukwu

**Comment by brucellino** [comment]
Looks good.
