### ISSUE TITLE
password issue

### ISSUE THREAD

**Issue by trinitysege** [sci-gaia/LagosHackfest#57]
I try to log-in with my username on futuregateway several time, but I was unable to and I always get a response say 'Sorry, try again.'

**Comment by brucellino** [comment]
Hi @trinitysege can you give us some more information please - which gateway are you using ?

**Comment by trinitysege** [comment]
I'm using sgw-dev.sci-gaia. eu

Hope it helps you understand?
On 16 Jan 2017 02:20, "Bruce Becker" <notifications@github.com> wrote:

Hi @trinitysege <https://github.com/trinitysege> can you give us some more
information please - which gateway are you using ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sci-gaia/LagosHackfest/issues/57#issuecomment-272823225>,
or mute the thread

**Comment by brucellino** [comment]
This issue was moved to http://discourse.sci-gaia.eu/t/password-issue/2450

**Comment by brucellino** [comment]
hi @trinitysege Thanks for  the feedback.

As far as I know, the site with the dev services has been decommissioned after the Lagos hackfest. @mtorrisi  can give you more detailed info, I think. I'm going to close this issue for now, and move it to Discourse. We can continue the discussion there.

**Comment by trinitysege** [comment]
Okay
